In [5]:
import numpy as np

1.Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [6]:
a = np.array([i for i in range (12,24)], dtype = int)
print (a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2.Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [27]:
np.reshape(a, (2,6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
np.reshape(a, (2,6), order = 'F')

array([[12, 14, 16, 18, 20, 22],
       [13, 15, 17, 19, 21, 23]])

In [31]:
np.reshape(a, (6,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [32]:
np.reshape(a, (3,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
np.reshape(a, (4,3), order = 'C')

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [41]:
np.reshape (a, (2,-1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
np.reshape (a, (3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
np.reshape (a, (-1,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [44]:
np.reshape (a, (-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [46]:
np.reshape (a, (-1,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
a.ndim

1

4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным

In [46]:
d = np.reshape(a, (-1,1))
d

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [47]:
d.ndim

2

In [51]:
d.shape

(10, 1)

In [ ]:
Массив из одного столбца и 12 строк нельзя назвать одномерным

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [11]:
a = np.random.sample((3,4))

In [12]:
a

array([[0.08111188, 0.28768926, 0.04812475, 0.84326937],
       [0.6834413 , 0.88601924, 0.56670377, 0.99648372],
       [0.04117106, 0.86778516, 0.59839534, 0.67480756]])

In [10]:
a.size

12

In [16]:
b = np.reshape(a,(-1,1))
b

array([[0.08111188],
       [0.28768926],
       [0.04812475],
       [0.84326937],
       [0.6834413 ],
       [0.88601924],
       [0.56670377],
       [0.99648372],
       [0.04117106],
       [0.86778516],
       [0.59839534],
       [0.67480756]])

In [17]:
b.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [18]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [41]:
b = np.reshape(np.arange(20,1,-2),(-1,1))
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [42]:
a.ndim

1

In [43]:
b.ndim

2

Разница в том, что массив а - одномерный, b - двумерный.

7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [82]:
a= np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [83]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [84]:
v = np.vstack((a,b))

In [85]:
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [86]:
v.size

10

8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [132]:
a = np.array([i for i in range (12)], dtype = int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [133]:
A = np.reshape(a,(4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [134]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [135]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [136]:
B.size

16

In [159]:
np.linalg.det(B)


0.0

определитель матрицы B = 0. обратную матрицу для B вычислить невозможно. 

In [139]:
B_inv = np.linalg.inv(B)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [143]:
np.random.seed(42)

In [146]:
c=np.random.randint(0,16,16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

In [147]:
C = np.reshape(c,(4,4))
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [155]:
C = np.dot(C,3)
C

array([[33, 27, 15, 36],
       [33, 24,  0, 30],
       [30, 42, 27, 45],
       [33, 33, 45, 42]])

In [156]:
B =([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [157]:
D = np.add(B, C)
D

array([[ 38,  41,  38,  68],
       [ 47,  74,  86, 152],
       [ 53, 128, 176, 257],
       [ 65, 155, 257, 344]])

In [158]:
np.linalg.det(D)

1878039.0000000002

In [161]:
np.linalg.matrix_rank(D)

4

In [162]:
D_inv = np.linalg.inv(D)

In [163]:
D_inv

array([[ 0.04543037,  0.00175875, -0.03937298,  0.01965774],
       [ 0.03117347, -0.06331498,  0.0840941 , -0.04101193],
       [ 0.03636825, -0.04778335, -0.00929693,  0.02087017],
       [-0.04980088,  0.06389484, -0.0235059 ,  0.00207983]])

Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [200]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a=[a.mean(axis=0)]
mean_a

[array([2. , 8.4])]

Задание 3
Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2

In [207]:
a_centered =np.array(np.subtract(a,mean_a))
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений

In [211]:
a_centered=np.sum()

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [215]:
a_centered_sp = np.dot(a_centered[:,1],a_centered[:,0])
np.diva_centered_sp

8.0